[plugin]
repository = "https://github.com/una-xiv/umbra.git"
commit = "515a0cda40113cd551b514c5e941c732ab5b73ad"
owners = [
    "haroldiedema",
    "alexpado",
    "Bloodsoul",
    "MeowZWR"
]
project_path = "Umbra"
