[plugin]
repository = "https://github.com/LittleNightmare/UsedName.git"
commit = "f1b574c31975fd5b172f8fda95d1932e14a23d38"
owners = [
    "LittleNightmare"
]
project_path = "UsedName"
changelog = """
- 可能损坏已有数据，请注意备份
- 有限支持7.0
- 命令`/pname update`暂时不可用
- 修复新人频道错误识别的问题
"""
