[plugin]
repository = "https://github.com/Bluefissure/PingPlugin.git"
commit = "935b9b0583063f28a075237bbff12a1e17b55667"
owners = ["karashiiro"]
changelog = """\
- Updated for API X
- Updated font handling
- Updated lobby server addresses
- Added fallback for Shadow ping detection
"""
