[plugin]
repository = "https://github.com/4679/XIVWindowResizer.git"
commit = "4930936fb02e63f9d61803264af2bcdfba211eeb"
owners = ["AlexCSDev", "4679"]
project_path = "XIVWindowResizer"
changelog = "CN 7.0"
