[plugin]
repository = "https://github.com/wozaiha/QoLBar.git"
commit = "f37b82e5a29f7dc00207a805b42c35c995a53842"
owners = [ "UnknownX7" ]
changelog = '''
- Updated for Dawntrail
- Fixed missing game symbols when the font size is not default'''
