[plugin]
repository = "https://github.com/decorwdyun/InventoryTools.git"
commit = "1c1ba3d5e83df643ece5687e8cc7fece2533b634"
owners = [
    "Critical-Impact",
    "decorwdyun"
]
project_path = "InventoryTools"
version = "1.7.0.21"
changelog = """\
### Fixed

- 国服适配

"""
