[plugin]
repository = "https://github.com/KirisameVanilla/HuntHelper.git"
commit = "28efdc2b41d89455a59a4997b181b4e159af5d8b"
owners = [
    "img02",
    "KirisameVanilla",
]
project_path = "HuntHelper"
