[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = 'a9f3cda594fcd75f8e814eb7b44e583121539e37'
owners = [ 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'Update for Dawntrail'
