[plugin]
repository = "https://github.com/zhouhuichen741/ffxiv-characterstatus-refined.git"
commit = "f8744e2a692771f11dd3b222c26fa4dac2a1fbb2"
owners = [
          "Kouzukii",
          "zhouhuichen741"
         ]
project_path = "CharacterPanelRefined"
changelog = """
- 本地化
"""
