[plugin]
repository = "https://github.com/shangxue12138/LogogramHelper-CN.git"
commit = "5006c97bbc39f5630634e713e547bd75e50dbe4c"
owners = ["apetih","shangxue12138"]
project_path = "LogogramHelper"
changelog = """
- Update for 7.0
"""
